version: '3.8'

services:
  arsenal-bot:
    build: .
    container_name: arsenal-bot-prod
    restart: unless-stopped
    
    # Variables d'environnement
    env_file:
      - .env
    
    environment:
      - ENV=production
      - PYTHONPATH=/app
      - TZ=Europe/Paris
    
    # Volumes pour persistance des données
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./backups:/app/backups
    
    # Configuration réseau (si monitoring web)
    ports:
      - "8080:8080"
    
    # Santé du conteneur
    healthcheck:
      test: ["CMD", "python", "-c", "import sys; sys.exit(0)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # Limites de ressources
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '0.5'
        reservations:
          memory: 512M
          cpus: '0.25'
    
    # Labels pour monitoring
    labels:
      - "com.docker.compose.service=arsenal-bot"
      - "maintainer=XeRoX"
      - "version=4.0"

  # Service de monitoring (optionnel)
  watchtower:
    image: containrrr/watchtower
    container_name: arsenal-watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=86400
      - WATCHTOWER_INCLUDE_RESTARTING=true
    command: arsenal-bot-prod

networks:
  default:
    name: arsenal-network
